name : coverage

on :
  push:
    branches:
      - milestone2
  pull_request:
    branches:
      - milestone2

  workflow_dispatch:


jobs:
  test_coverage:
    name: Test percent code coverage for entire package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: python -m pip install build pytest pytest-cov

      - name: Build and install project in container (using PEP517/518)
        run: (python -m build --wheel && python -m pip install dist/*)
        
      - name: Run tests and generate coverage html
        run: (cd tests && ./run_tests.sh CI --cov=bad_package --cov-report=term-missing)
